USE DataWarehouse
SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='dim_products'



--Generate a report higlighting all the important business metrics 
SELECT 
    'Total Sales' AS measure_name,
    SUM(sales_amount) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Total Items Sold' AS measure_name,
    SUM(quantity) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Avg Selling Price' AS measure_name,
    AVG(price) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Total Distinct Orders' AS measure_name,
    COUNT(DISTINCT order_number) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Total Number of Products' AS measure_name,
    COUNT(product_id) AS measure_value
FROM Gold.dim_products

UNION ALL

SELECT 
    'Total Number of Customers' AS measure_name,
    COUNT(customer_id) AS measure_value
FROM Gold.dim_customers

UNION ALL

SELECT 
    'Total Number of Customers with Purchases' AS measure_name,
    COUNT(DISTINCT customer_key) AS measure_value
FROM Gold.fact_sales;



--Generate a magnitude analysis report highlighting important business insights


--Find total customers by country
select count(customer_id) as country_count,coalesce(country,'Others') as country from gold.dim_customers group by country
order by count(customer_id) desc

--Find total customers by Gender
select count(customer_id) as cust_count,gender from gold.dim_customers group by gender order by count(customer_id) desc

--Find total products by category
select ISNULL(category,'Others'),count(product_id) from gold.dim_products group by category order by count(product_id) desc

--What is the average costs in each category?
select ISNULL(category,'Others'),avg(cost) from gold.dim_products group by category order by avg(cost)desc

--What is the total revenue generated for each category?
select p.category,sum(s.sales_amount) as category_sales from gold.dim_products as p left join
gold.fact_sales as s on p.product_key=s.product_key group by p.category order by sum(s.sales_amount) desc


--what is the total revenue generated by each customer?
select c.customer_key,c.first_name+c.last_name as FullName,sum(s.sales_amount) from Gold.dim_customers as c left join Gold.fact_sales as s 
on c.customer_key=s.customer_key group by c.customer_key,c.first_name,c.last_name order by sum(s.sales_amount) desc


--Which 5 products generate the highest revenue?
SELECT TOP 5 
    product_name,
    product_sales
FROM (
    SELECT 
        p.product_key,
        p.product_name,
        SUM(s.sales_amount) AS product_sales
    FROM Gold.dim_products AS p
    LEFT JOIN Gold.fact_sales AS s 
        ON p.product_key = s.product_key
    GROUP BY 
        p.product_key, 
        p.product_name
) t
WHERE product_sales IS NOT NULL
ORDER BY product_sales DESC;



--Which 5 products generate the lowest revenue?
SELECT TOP 5 
    product_name,
    product_sales
FROM (
    SELECT 
        p.product_key,
        p.product_name,
        SUM(s.sales_amount) AS product_sales
    FROM Gold.dim_products AS p
    LEFT JOIN Gold.fact_sales AS s 
        ON p.product_key = s.product_key
    GROUP BY 
        p.product_key, 
        p.product_name
) t
WHERE product_sales IS NOT NULL
ORDER BY product_sales;




--THESE WERE SOME OF THE EXAMPLES DEMONSTRATING HOW WE CAN EXPLORE THE DATA USING VARIOUS DIMENSIONS AND MEASURES.
