USE DataWarehouse;

-- Explore metadata
SELECT * 
FROM INFORMATION_SCHEMA.TABLES;

SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'dim_products';


/*
===============================================================
Generate a report highlighting all the important business metrics
===============================================================
*/
SELECT 
    'Total Sales' AS measure_name,
    SUM(sales_amount) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Total Items Sold' AS measure_name,
    SUM(quantity) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Avg Selling Price' AS measure_name,
    AVG(price) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Total Distinct Orders' AS measure_name,
    COUNT(DISTINCT order_number) AS measure_value
FROM Gold.fact_sales

UNION ALL

SELECT 
    'Total Number of Products' AS measure_name,
    COUNT(product_id) AS measure_value
FROM Gold.dim_products

UNION ALL

SELECT 
    'Total Number of Customers' AS measure_name,
    COUNT(customer_id) AS measure_value
FROM Gold.dim_customers

UNION ALL

SELECT 
    'Total Number of Customers with Purchases' AS measure_name,
    COUNT(DISTINCT customer_key) AS measure_value
FROM Gold.fact_sales;


/*
===============================================================
Generate a magnitude analysis report highlighting key insights
===============================================================
*/

-- Find total customers by country
SELECT 
    COUNT(customer_id) AS country_count,
    COALESCE(country, 'Others') AS country
FROM Gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_id) DESC;

-- Find total customers by gender
SELECT 
    COUNT(customer_id) AS cust_count,
    gender
FROM Gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_id) DESC;

-- Find total products by category
SELECT 
    ISNULL(category, 'Others') AS category,
    COUNT(product_id) AS product_count
FROM Gold.dim_products
GROUP BY category
ORDER BY COUNT(product_id) DESC;

-- What is the average cost in each category?
SELECT 
    ISNULL(category, 'Others') AS category,
    AVG(cost) AS avg_cost
FROM Gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC;

-- What is the total revenue generated for each category?
SELECT 
    p.category,
    SUM(s.sales_amount) AS category_sales
FROM Gold.dim_products AS p
LEFT JOIN Gold.fact_sales AS s 
    ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY SUM(s.sales_amount) DESC;

-- What is the total revenue generated by each customer?
SELECT 
    c.customer_key,
    c.first_name + c.last_name AS FullName,
    SUM(s.sales_amount) AS total_revenue
FROM Gold.dim_customers AS c
LEFT JOIN Gold.fact_sales AS s 
    ON c.customer_key = s.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY SUM(s.sales_amount) DESC;

-- Which 5 products generate the highest revenue?
SELECT TOP 5 
    product_name,
    product_sales
FROM (
    SELECT 
        p.product_key,
        p.product_name,
        SUM(s.sales_amount) AS product_sales
    FROM Gold.dim_products AS p
    LEFT JOIN Gold.fact_sales AS s 
        ON p.product_key = s.product_key
    GROUP BY 
        p.product_key, 
        p.product_name
) t
WHERE product_sales IS NOT NULL
ORDER BY product_sales DESC;

-- Which 5 products generate the lowest revenue?
SELECT TOP 5 
    product_name,
    product_sales
FROM (
    SELECT 
        p.product_key,
        p.product_name,
        SUM(s.sales_amount) AS product_sales
    FROM Gold.dim_products AS p
    LEFT JOIN Gold.fact_sales AS s 
        ON p.product_key = s.product_key
    GROUP BY 
        p.product_key, 
        p.product_name
) t
WHERE product_sales IS NOT NULL
ORDER BY product_sales ASC;

--THESE WERE SOME OF THE EXAMPLES DEMONSTRATING HOW WE CAN EXPLORE THE DATA USING VARIOUS DIMENSIONS AND MEASURES.
